/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.16
 * Generated at: 2022-03-08 07:29:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MessageUS;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.project.connection.ConnectionProvider;
import java.sql.*;

public final class messageus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.connection.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Contact Form 02</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700'\r\n");
      out.write("	rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Lobster&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<section class=\"ftco-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-6 text-center mb-5\">\r\n");
      out.write("					<h1 class=\"brand\" style=\"font-family: 'Lobster', cursive;\">kitchen\r\n");
      out.write("						Story</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-12\">\r\n");
      out.write("					<div class=\"wrapper\">\r\n");
      out.write("						<div class=\"row no-gutters\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"col-lg-8 col-md-7 order-md-last d-flex align-items-stretch\">\r\n");
      out.write("								<div class=\"contact-wrap w-100 p-md-5 p-4\">\r\n");
      out.write("									<h3 class=\"mb-4\">Get in touch</h3>\r\n");
      out.write("									<div id=\"form-message-warning\" class=\"mb-4\"></div>\r\n");
      out.write("									<div id=\"form-message-success\" class=\"mb-4\">Your message\r\n");
      out.write("										was sent, thank you!</div>\r\n");
      out.write("									<form method=\"POST\" id=\"contactForm\" name=\"contactForm\"\r\n");
      out.write("										class=\"contactForm\" action=\"messageusAction.jsp\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-md-6\">\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<label class=\"label\" for=\"name\">Full Name</label> <input\r\n");
      out.write("														type=\"text\" class=\"form-control\" name=\"name\" id=\"name\"\r\n");
      out.write("														placeholder=\"Name\">\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-6\">\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<label class=\"label\" for=\"email\">Email Address</label> <input\r\n");
      out.write("														type=\"email\" class=\"form-control\" name=\"email\" id=\"email\"\r\n");
      out.write("														placeholder=\"Email\">\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-12\">\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<label class=\"label\" for=\"subject\">Subject</label> <input\r\n");
      out.write("														type=\"text\" class=\"form-control\" name=\"subject\"\r\n");
      out.write("														id=\"subject\" placeholder=\"Subject\">\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-12\">\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<label class=\"label\" for=\"#\">Message</label>\r\n");
      out.write("													<textarea name=\"body\" class=\"form-control\" id=\"message\"\r\n");
      out.write("														cols=\"30\" rows=\"4\" placeholder=\"Message\"></textarea>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-12\">\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<input type=\"submit\" value=\"Send Message\"\r\n");
      out.write("														class=\"btn btn-primary\">\r\n");
      out.write("													<div class=\"submitting\"></div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-4 col-md-5 d-flex align-items-stretch\">\r\n");
      out.write("								<div class=\"info-wrap bg-primary w-100 p-md-5 p-4\">\r\n");
      out.write("									<h3>Let's get in touch</h3>\r\n");
      out.write("									<p class=\"mb-4\">We're open for any suggestion or just to\r\n");
      out.write("										have a chat</p>\r\n");
      out.write("									<div class=\"dbox w-100 d-flex align-items-start\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("											<span class=\"fa fa-map-marker\"></span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"text pl-3\">\r\n");
      out.write("											<p>\r\n");
      out.write("												<span>Address:</span> 198 West 21th Street, Suite 721 New\r\n");
      out.write("												York NY 10016\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dbox w-100 d-flex align-items-center\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("											<span class=\"fa fa-phone\"></span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"text pl-3\">\r\n");
      out.write("											<p>\r\n");
      out.write("												<span>Phone:</span> <a href=\"tel://1234567920\">+ 1235\r\n");
      out.write("													2355 98</a>\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dbox w-100 d-flex align-items-center\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("											<span class=\"fa fa-paper-plane\"></span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"text pl-3\">\r\n");
      out.write("											<p>\r\n");
      out.write("												<span>Email:</span> <a href=\"mailto:info@yoursite.com\">kitchenstory789@gmail.com</a>\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dbox w-100 d-flex align-items-center\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("											<span class=\"fa fa-globe\"></span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"text pl-3\">\r\n");
      out.write("											<p>\r\n");
      out.write("												<span>Website</span> <a href=\"#\">kitchenstory.com</a>\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"js/popper.js\"></script>\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
