/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.16
 * Generated at: 2022-03-11 08:48:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class productsPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1646983617222L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Family -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lobster&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/indexStyle.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- font awesome -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/c26cd2166c.js\"></script>\r\n");
      out.write("    <title>Kitchen Story | Home</title>\r\n");
      out.write("</head>\r\n");
String email=session.getAttribute("email").toString(); 
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"#\">Kitchen Story</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarScroll\" aria-controls=\"navbarScroll\"\r\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarScroll\">\r\n");
      out.write("			<ul class=\"navbar-nav m-auto my-2 my-lg-0\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\" href=\"home.jsp\">Home</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#trending\">My\r\n");
      out.write("						Cart</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#store\"> My\r\n");
      out.write("						Orders </a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"home.jsp#aboutUs\">About Us</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"messageus.jsp\">Message\r\n");
      out.write("						Us</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"  id=\"accName\" href=\"Account.jsp\">");
      out.print(email);
      out.write("</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"logoutAction.jsp\" style=\"color: red; text-transform:capitalize;\"><u>Logout</u></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<form class=\"d-flex\">\r\n");
      out.write("				<input class=\"px-2 search\" type=\"search\" placeholder=\"Search\"\r\n");
      out.write("					aria-label=\"Search\">\r\n");
      out.write("				<button class=\"btn0\" type=\"submit\">Search</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"productsStyle.css\">\r\n");
      out.write("<!-- font awesome -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/dbed6b6114.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"products\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h1 class=\"lg-title\" style=\"color: rgb(248, 26, 92)\">Delicious Dishes with Delicious Offers</h1>\r\n");
      out.write("			<p class=\"text-light\" style=\"color: rgb(248, 26, 92)\">Lorem ipsum dolor sit amet consectetur\r\n");
      out.write("				adipisicing elit. Aspernatur quos sit consectetur, ipsa voluptatem\r\n");
      out.write("				vitae necessitatibus dicta veniam, optio, possimus assumenda\r\n");
      out.write("				laudantium. Temporibus, quis cum.</p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"product-items\">\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/biryani-products.jpg\" alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Biryani</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Chicken Dum Biryani</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"off-info\">\r\n");
      out.write("						<h2 class=\"sm-title\">25% off</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/bonelessChicken-products.jpg\"\r\n");
      out.write("								alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Chicken</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Boneless Chicken Breast</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/frenchFries-products.jpg\" alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Fries</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Potato French Fries</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/fish-products.jpg\" alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Fish</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Apollo Fish Boneless</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"off-info\">\r\n");
      out.write("						<h2 class=\"sm-title\">25% off</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/fish-products.jpg\" alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Fish</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Apollo Fish Boneless</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/frenchFries-products.jpg\" alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Fries</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Potato French Fries</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/bonelessChicken-products.jpg\"\r\n");
      out.write("								alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">chicken</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Boneless Chicken Breast</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("				<!-- single product -->\r\n");
      out.write("				<div class=\"product\">\r\n");
      out.write("					<div class=\"product-content\">\r\n");
      out.write("						<div class=\"product-img\">\r\n");
      out.write("							<img src=\"images/biryani-products.jpg\" alt=\"product image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-btns\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-cart\">\r\n");
      out.write("								add to cart <span><i class=\"fas fa-plus\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn-buy\">\r\n");
      out.write("								buy now <span><i class=\"fas fa-shopping-cart\"></i></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-info\">\r\n");
      out.write("						<div class=\"product-info-top\">\r\n");
      out.write("							<h2 class=\"sm-title\">Biryani</h2>\r\n");
      out.write("							<div class=\"rating\">\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"fas fa-star\"></i></span> <span><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("								<span><i class=\"fas fa-star\"></i></span> <span><i\r\n");
      out.write("									class=\"far fa-star\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"#\" class=\"product-name\">Chicken Dum Biryani</a>\r\n");
      out.write("						<p class=\"product-price\">$ 150.00</p>\r\n");
      out.write("						<p class=\"product-price\">$ 133.00</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"off-info\">\r\n");
      out.write("						<h2 class=\"sm-title\">35% off</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end of single product -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"product-collection\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"product-collection-wrapper\">\r\n");
      out.write("				<!-- product col left -->\r\n");
      out.write("				<div class=\"product-col-left flex\">\r\n");
      out.write("					<div class=\"product-col-content\">\r\n");
      out.write("						<h2 class=\"sm-title\">Natural Veggies</h2>\r\n");
      out.write("						<h2 class=\"md-title\">Natural Veggies</h2>\r\n");
      out.write("						<p class=\"text-light\">Lorem ipsum dolor sit, amet consectetur\r\n");
      out.write("							adipisicing elit. Molestiae consequatur facilis eligendi\r\n");
      out.write("							quibusdam voluptatibus exercitationem autem voluptatum, beatae\r\n");
      out.write("							architecto odit, quisquam repellat. Deleniti, architecto ab.</p>\r\n");
      out.write("						<button type=\"button\" class=\"btn-dark\">Shop now</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- product col right -->\r\n");
      out.write("				<div class=\"product-col-right\">\r\n");
      out.write("					<div class=\"product-col-r-top flex\">\r\n");
      out.write("						<div class=\"product-col-content\">\r\n");
      out.write("							<h2 class=\"sm-title\">Fresh Juicy Fruits</h2>\r\n");
      out.write("							<h2 class=\"md-title\">Fruits and Fun</h2>\r\n");
      out.write("							<p class=\"text-light\">Lorem ipsum dolor sit, amet consectetur\r\n");
      out.write("								adipisicing elit. Molestiae consequatur facilis eligendi\r\n");
      out.write("								quibusdam voluptatibus exercitationem autem voluptatum, beatae\r\n");
      out.write("								architecto odit, quisquam repellat. Deleniti, architecto ab.</p>\r\n");
      out.write("							<button type=\"button\" class=\"btn-dark\">Shop now</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product-col-r-bottom\">\r\n");
      out.write("						<!-- left -->\r\n");
      out.write("						<div class=\"flex\">\r\n");
      out.write("							<div class=\"product-col-content\">\r\n");
      out.write("								<h2 class=\"sm-title\">summer sale</h2>\r\n");
      out.write("								<h2 class=\"md-title\">Extra 50% Off</h2>\r\n");
      out.write("								<p class=\"text-light\">Lorem ipsum dolor sit, amet\r\n");
      out.write("									consectetur adipisicing elit. Molestiae consequatur facilis\r\n");
      out.write("									eligendi quibusdam voluptatibus exercitationem autem\r\n");
      out.write("									voluptatum, beatae architecto odit, quisquam repellat.\r\n");
      out.write("									Deleniti, architecto ab.</p>\r\n");
      out.write("								<button type=\"button\" class=\"btn-dark\">Shop now</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- right -->\r\n");
      out.write("						<div class=\"flex\">\r\n");
      out.write("							<div class=\"product-col-content\">\r\n");
      out.write("								<h2 class=\"sm-title\">shoes</h2>\r\n");
      out.write("								<h2 class=\"md-title\">best sellers</h2>\r\n");
      out.write("								<p class=\"text-light\">Lorem ipsum dolor sit, amet\r\n");
      out.write("									consectetur adipisicing elit. Molestiae consequatur facilis\r\n");
      out.write("									eligendi quibusdam voluptatibus exercitationem autem\r\n");
      out.write("									voluptatum, beatae architecto odit, quisquam repellat.\r\n");
      out.write("									Deleniti, architecto ab.</p>\r\n");
      out.write("								<button type=\"button\" class=\"btn-dark\">Shop now</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
